/**
 * Test to determine if verifySignature works correctly with keys
 * generated by this library (same flow WhatsApp would use).
 *
 * The question: was `isInit=true` (skip verification) necessary?
 * If these tests pass, verification works and isInit was a bug.
 * If they fail, WhatsApp may need the bypass.
 */
import { describe, it, expect } from 'vitest'
import curve from '../../src/crypto/curve'
import * as keyhelper from '../../src/crypto/keyhelper'

describe('verifySignature compatibility (WhatsApp scenario)', () => {
  it('should verify signed prekey created by generateSignedPreKey', () => {
    // This simulates what WhatsApp does:
    // 1. Generate identity key pair
    // 2. Generate signed prekey (signs pubKey with identity privKey)
    // 3. Send to other party
    // 4. Other party verifies signature using identity pubKey

    const identityKeyPair = keyhelper.generateIdentityKeyPair()
    const signedPreKey = keyhelper.generateSignedPreKey(identityKeyPair, 1)

    // This is exactly what initOutgoing does now (without isInit bypass)
    const isValid = curve.verifySignature(identityKeyPair.pubKey, signedPreKey.keyPair.pubKey, signedPreKey.signature)

    expect(isValid).toBe(true)
  })

  it('should verify across multiple key generations (100 rounds)', () => {
    // Run many iterations to ensure it's not flaky
    for (let i = 0; i < 100; i++) {
      const identity = keyhelper.generateIdentityKeyPair()
      const signed = keyhelper.generateSignedPreKey(identity, i)

      const isValid = curve.verifySignature(identity.pubKey, signed.keyPair.pubKey, signed.signature)

      expect(isValid, `Failed at round ${i}`).toBe(true)
    }
  })

  it('should reject signature from different identity key', () => {
    const identity1 = keyhelper.generateIdentityKeyPair()
    const identity2 = keyhelper.generateIdentityKeyPair()
    const signed = keyhelper.generateSignedPreKey(identity1, 1)

    // Verify with wrong identity — MUST fail
    const isValid = curve.verifySignature(identity2.pubKey, signed.keyPair.pubKey, signed.signature)

    expect(isValid).toBe(false)
  })

  it('should reject tampered signed prekey public key', () => {
    const identity = keyhelper.generateIdentityKeyPair()
    const signed = keyhelper.generateSignedPreKey(identity, 1)

    // Tamper the signed prekey's public key
    const tamperedPubKey = Buffer.from(signed.keyPair.pubKey)
    tamperedPubKey[10] ^= 0xff

    const isValid = curve.verifySignature(identity.pubKey, tamperedPubKey, signed.signature)

    expect(isValid).toBe(false)
  })

  it('should work with the full initOutgoing flow', () => {
    // Simulate Bob's device bundle exactly as WhatsApp would provide
    const bobIdentity = keyhelper.generateIdentityKeyPair()
    const bobSignedPreKey = keyhelper.generateSignedPreKey(bobIdentity, 1)
    const bobPreKey = keyhelper.generatePreKey(1)

    // This is what initOutgoing does:
    // curve.verifySignature(device.identityKey, device.signedPreKey.publicKey, device.signedPreKey.signature)
    const isValid = curve.verifySignature(
      bobIdentity.pubKey, // device.identityKey
      bobSignedPreKey.keyPair.pubKey, // device.signedPreKey.publicKey
      bobSignedPreKey.signature, // device.signedPreKey.signature
    )

    expect(isValid).toBe(true)
  })
})
